version: 2.1
jobs:
  test_and_build:
    docker:
      - image: cimg/go:1.18
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout:
          path: ~/go/src/github.com/canalun/sqloth
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: Build App
          command: go build
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - test_and_build