// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canalun/sqloth/domain/driver (interfaces: Driver)

// Package mock_driver is a generated GoMock package.
package mock_driver

import (
	reflect "reflect"

	model "github.com/canalun/sqloth/domain/model"
	gomock "github.com/golang/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// GetSchema mocks base method.
func (m *MockDriver) GetSchema() model.Schema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema")
	ret0, _ := ret[0].(model.Schema)
	return ret0
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockDriverMockRecorder) GetSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockDriver)(nil).GetSchema))
}